spring:
  application:
    name: api-gateway
server:
  port: 2006
zuul:
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 5000
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000